apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"

rules:
  - level: Metadata
    userGroups: ["system:nodes"]

  # Log configmap and secret changes in all other namespaces at the Metadata level.
  - level: Metadata
    resources:
    - group: "" # core API group
      resources: ["secrets"]

  - level: Metadata
    resources:
    - group: ""
      resources: ["pods/log", "pods/exec"]
  
  - level: None
